import Link from 'next/link';
import {BookOpen,Flag,Megaphone,Users,ShieldCheck,ArrowRight,CalendarDays} from 'lucide-react';
import {createSupabaseServerClient} from '@/lib/supabase/server';
export const metadata={title:'Admin'};
export default async function Admin(){
  let email:string|undefined,role:string|undefined,counts={tracks:0,missions:0,submissions:0,learners:0};
  if(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();email=user?.email;role=user?.app_metadata?.role as string|undefined;if(role==='admin'){const [tracks,missions,submissions,learners]=await Promise.all([supabase.from('learning_tracks').select('*',{count:'exact',head:true}),supabase.from('missions').select('*',{count:'exact',head:true}),supabase.from('submissions').select('*',{count:'exact',head:true}),supabase.from('profiles').select('*',{count:'exact',head:true})]);counts={tracks:tracks.count||0,missions:missions.count||0,submissions:submissions.count||0,learners:learners.count||0}}}
  if(!email)return <section className="shell section"><span className="eyebrow">Admin portal</span><h1>Sign in to continue.</h1><Link href="/login?next=/admin" className="btn btn-primary">Open login</Link></section>;
  if(role!=='admin')return <section className="shell section"><span className="eyebrow">Admin portal</span><h1>Admin access is restricted.</h1><p className="lede">Signed in as {email}. Ask an existing admin to add this address on the Admin team page — you will be an admin the next time you sign in.</p><Link href="/dashboard" className="btn btn-secondary">Back to Learning Hub</Link></section>;
  const items=[[BookOpen,'Content library','Tracks and missions',`${counts.tracks} tracks · ${counts.missions} missions`,'/admin/content'],[CalendarDays,'Events & bootcamps','Create events and manage registrations','Flyers, Luma links and exports','/admin/events'],[Users,'Learners & applications','Member access and applications',`${counts.learners} registered learners`,'/admin/inquiries'],[Flag,'Submissions','Review learner evidence',`${counts.submissions} submissions in queue`,'/admin/submissions'],[Megaphone,'Announcements','Send updates through Resend','Email all opted-in community contacts','/admin/announcements'],[ShieldCheck,'Admin team','Invite and remove admins','Access is granted by Google sign-in','/admin/admins']] as const;
  return <section className="shell section"><span className="eyebrow">Operations</span><h1 style={{fontSize:'clamp(38px,6vw,64px)',letterSpacing:'-.07em'}}>Keep the learning loop healthy.</h1><p className="lede">Your operational view is connected to the live Supabase data.</p><div className="grid admin-grid" style={{marginTop:38}}>{items.map(([Icon,title,description,detail,href])=><Link href={href} className="card" style={{padding:23}} key={title}><Icon color="var(--brand)"/><h2 style={{fontSize:21,margin:'15px 0 7px'}}>{title}</h2><p className="lede" style={{fontSize:13}}>{description}</p><small style={{display:'block',color:'var(--muted)',marginBottom:15}}>{detail}</small><span className="btn btn-secondary">Open <ArrowRight size={15}/></span></Link>)}</div><div className="card" style={{padding:22,marginTop:30,display:'flex',gap:13,alignItems:'center'}}><ShieldCheck color="var(--brand)"/><p style={{fontSize:13,margin:0}}>Free-course operations are live. Payments are intentionally disabled until a later phase.</p></div><style>{`.admin-grid{grid-template-columns:repeat(2,1fr)}@media(max-width:700px){.admin-grid{grid-template-columns:1fr}}`}</style></section>;
}
