-- HandsOn Academy Phase 4/5 foundation. Run in Supabase SQL Editor or via Supabase CLI.
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.learning_tracks (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, category text not null, description text not null, created_at timestamptz not null default now());
create table if not exists public.missions (id text primary key, track_slug text not null references public.learning_tracks(slug) on delete cascade, milestone text not null, title text not null, objective text not null, estimated_minutes integer not null default 30, tasks jsonb not null default '[]'::jsonb, commands jsonb not null default '[]'::jsonb, expected_outcome text not null, hint text not null, sort_order integer not null default 0);
create table if not exists public.mission_progress (user_id uuid not null references auth.users(id) on delete cascade, mission_id text not null references public.missions(id) on delete cascade, status text not null default 'not_started' check (status in ('not_started','in_progress','completed')), completed_at timestamptz, updated_at timestamptz not null default now(), primary key (user_id, mission_id));
create table if not exists public.submissions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, mission_id text not null references public.missions(id) on delete cascade, evidence text not null check (char_length(evidence) between 1 and 10000), status text not null default 'pending' check (status in ('pending','approved','needs_changes')), reviewer_notes text, created_at timestamptz not null default now(), reviewed_at timestamptz);
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), title text not null, body text not null, published boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.community_inquiries (id uuid primary key default gen_random_uuid(), kind text not null check (kind in ('sponsor','mentor','learner')), full_name text not null, email text not null, phone text not null, country text, organization text, focus text, message text not null, status text not null default 'new' check (status in ('new','contacted','closed')), admin_notes text, created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.learning_tracks enable row level security; alter table public.missions enable row level security; alter table public.mission_progress enable row level security; alter table public.submissions enable row level security; alter table public.announcements enable row level security; alter table public.community_inquiries enable row level security;
drop policy if exists "users read own profile" on public.profiles; drop policy if exists "users insert own profile" on public.profiles; drop policy if exists "users update own profile" on public.profiles; drop policy if exists "public tracks readable" on public.learning_tracks; drop policy if exists "public missions readable" on public.missions; drop policy if exists "users read own progress" on public.mission_progress; drop policy if exists "users write own progress" on public.mission_progress; drop policy if exists "users update own progress" on public.mission_progress; drop policy if exists "users read own submissions" on public.submissions; drop policy if exists "users create own submissions" on public.submissions; drop policy if exists "admins read submissions" on public.submissions; drop policy if exists "admins update submissions" on public.submissions; drop policy if exists "admins read all progress" on public.mission_progress; drop policy if exists "published announcements readable" on public.announcements;
drop policy if exists "anyone create inquiries" on public.community_inquiries; drop policy if exists "admins read inquiries" on public.community_inquiries; drop policy if exists "admins update inquiries" on public.community_inquiries;
create policy "anyone create inquiries" on public.community_inquiries for insert with check (true);
create policy "admins read inquiries" on public.community_inquiries for select using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins update inquiries" on public.community_inquiries for update using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "users insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "public tracks readable" on public.learning_tracks for select using (true);
create policy "public missions readable" on public.missions for select using (true);
create policy "users read own progress" on public.mission_progress for select using (auth.uid() = user_id);
create policy "users write own progress" on public.mission_progress for insert with check (auth.uid() = user_id);
create policy "users update own progress" on public.mission_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users read own submissions" on public.submissions for select using (auth.uid() = user_id);
create policy "users create own submissions" on public.submissions for insert with check (auth.uid() = user_id);
create policy "admins read submissions" on public.submissions for select using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins update submissions" on public.submissions for update using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins read all progress" on public.mission_progress for select using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "published announcements readable" on public.announcements for select using (published = true or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
insert into public.learning_tracks (slug,title,category,description) values ('devops-beginner','DevOps Beginner','DevOps','Linux web stack deployment'),('cloud-native-beginner','Cloud Native Beginner','Cloud Native','Docker 101') on conflict (slug) do nothing;
insert into public.missions (id,track_slug,milestone,title,objective,estimated_minutes,tasks,commands,expected_outcome,hint,sort_order) values
('linux-shell-basics','devops-beginner','Prepare your Linux environment','Navigate the terminal with confidence','Use the shell to inspect your environment and create a workspace.',45,'["Open a terminal session","Create a handson-workspace directory","Record your OS and shell versions","Write a short notes file"]','["mkdir -p ~/handson-workspace","uname -a","echo shell-version","touch ~/handson-workspace/notes.md"]','A workspace directory containing notes.md.','Check that your home directory is writable.',1),
('flask-health-route','devops-beginner','Build and run a Flask application','Ship a health endpoint','Run a small Flask service and verify its response.',60,'["Create a virtual environment","Install Flask","Expose GET /health","Use curl to verify the response"]','["python3 -m venv .venv","source .venv/bin/activate","pip install flask","curl http://127.0.0.1:5000/health"]','The endpoint responds successfully.','Activate the virtual environment before installing.',2),
('docker-first-container','cloud-native-beginner','Hands-On Docker Basics','Run your first container','Pull an image, run it locally, and inspect its lifecycle.',45,'["Check Docker is available","Run an nginx container","List running containers","Stop and remove the container"]','["docker run -d --name hands-on-nginx -p 8080:80 nginx","docker ps","docker stop hands-on-nginx","docker rm hands-on-nginx"]','The nginx page is available at localhost:8080.','Use another local port if 8080 is busy.',1) on conflict (id) do nothing;
