-- HandsOn Academy Phase 4/5 foundation. Run in Supabase SQL Editor or via Supabase CLI.
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.learning_tracks (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, category text not null, description text not null, created_at timestamptz not null default now());
create table if not exists public.missions (id text primary key, track_slug text not null references public.learning_tracks(slug) on delete cascade, milestone text not null, title text not null, objective text not null, estimated_minutes integer not null default 30, tasks jsonb not null default '[]'::jsonb, commands jsonb not null default '[]'::jsonb, expected_outcome text not null, hint text not null, sort_order integer not null default 0);
create table if not exists public.mission_progress (user_id uuid not null references auth.users(id) on delete cascade, mission_id text not null references public.missions(id) on delete cascade, status text not null default 'not_started' check (status in ('not_started','in_progress','completed')), completed_at timestamptz, updated_at timestamptz not null default now(), primary key (user_id, mission_id));
create table if not exists public.submissions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, mission_id text not null references public.missions(id) on delete cascade, evidence text not null check (char_length(evidence) between 1 and 10000), status text not null default 'pending' check (status in ('pending','approved','needs_changes')), reviewer_notes text, created_at timestamptz not null default now(), reviewed_at timestamptz);
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), title text not null, body text not null, published boolean not null default false, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.community_inquiries (id uuid primary key default gen_random_uuid(), kind text not null check (kind in ('sponsor','mentor','learner')), full_name text not null, email text not null, phone text not null, country text, organization text, focus text, message text not null, consent boolean not null default false, status text not null default 'new' check (status in ('new','approved','rejected','blocked','contacted','closed')), admin_notes text, created_at timestamptz not null default now());
alter table public.community_inquiries add column if not exists consent boolean not null default false; alter table public.community_inquiries drop constraint if exists community_inquiries_status_check; alter table public.community_inquiries add constraint community_inquiries_status_check check (status in ('new','approved','rejected','blocked','contacted','closed'));
alter table public.profiles enable row level security; alter table public.learning_tracks enable row level security; alter table public.missions enable row level security; alter table public.mission_progress enable row level security; alter table public.submissions enable row level security; alter table public.announcements enable row level security; alter table public.community_inquiries enable row level security;
drop policy if exists "users read own profile" on public.profiles; drop policy if exists "users insert own profile" on public.profiles; drop policy if exists "users update own profile" on public.profiles; drop policy if exists "public tracks readable" on public.learning_tracks; drop policy if exists "public missions readable" on public.missions; drop policy if exists "users read own progress" on public.mission_progress; drop policy if exists "users write own progress" on public.mission_progress; drop policy if exists "users update own progress" on public.mission_progress; drop policy if exists "users read own submissions" on public.submissions; drop policy if exists "users create own submissions" on public.submissions; drop policy if exists "admins read submissions" on public.submissions; drop policy if exists "admins update submissions" on public.submissions; drop policy if exists "admins read all progress" on public.mission_progress; drop policy if exists "published announcements readable" on public.announcements;
drop policy if exists "anyone create inquiries" on public.community_inquiries; drop policy if exists "applicants read own application" on public.community_inquiries; drop policy if exists "admins read inquiries" on public.community_inquiries; drop policy if exists "admins update inquiries" on public.community_inquiries;
create policy "anyone create inquiries" on public.community_inquiries for insert with check (true);
create policy "applicants read own application" on public.community_inquiries for select using (lower(email) = lower((select auth.jwt() ->> 'email')) and kind = 'learner');
create policy "admins read inquiries" on public.community_inquiries for select using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins update inquiries" on public.community_inquiries for update using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "users insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "public tracks readable" on public.learning_tracks for select using (true);
create policy "public missions readable" on public.missions for select using (true);
create policy "users read own progress" on public.mission_progress for select using (auth.uid() = user_id);
create policy "users write own progress" on public.mission_progress for insert with check (auth.uid() = user_id);
create policy "users update own progress" on public.mission_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users read own submissions" on public.submissions for select using (auth.uid() = user_id);
create policy "users create own submissions" on public.submissions for insert with check (auth.uid() = user_id);
create policy "admins read submissions" on public.submissions for select using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins update submissions" on public.submissions for update using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "admins read all progress" on public.mission_progress for select using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
create policy "published announcements readable" on public.announcements for select using (published = true or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
insert into public.learning_tracks (slug,title,category,description) values ('devops-beginner','DevOps Beginner','DevOps','Linux web stack deployment'),('cloud-native-beginner','Cloud Native Beginner','Cloud Native','Docker 101') on conflict (slug) do nothing;
insert into public.missions (id,track_slug,milestone,title,objective,estimated_minutes,tasks,commands,expected_outcome,hint,sort_order) values
('linux-shell-basics','devops-beginner','Prepare your Linux environment','Navigate the terminal with confidence','Use the shell to inspect your environment and create a workspace.',45,'["Open a terminal session","Create a handson-workspace directory","Record your OS and shell versions","Write a short notes file"]','["mkdir -p ~/handson-workspace","uname -a","echo shell-version","touch ~/handson-workspace/notes.md"]','A workspace directory containing notes.md.','Check that your home directory is writable.',1),
('flask-health-route','devops-beginner','Build and run a Flask application','Ship a health endpoint','Run a small Flask service and verify its response.',60,'["Create a virtual environment","Install Flask","Expose GET /health","Use curl to verify the response"]','["python3 -m venv .venv","source .venv/bin/activate","pip install flask","curl http://127.0.0.1:5000/health"]','The endpoint responds successfully.','Activate the virtual environment before installing.',2),
('docker-first-container','cloud-native-beginner','Hands-On Docker Basics','Run your first container','Pull an image, run it locally, and inspect its lifecycle.',45,'["Check Docker is available","Run an nginx container","List running containers","Stop and remove the container"]','["docker run -d --name hands-on-nginx -p 8080:80 nginx","docker ps","docker stop hands-on-nginx","docker rm hands-on-nginx"]','The nginx page is available at localhost:8080.','Use another local port if 8080 is busy.',1) on conflict (id) do nothing;
insert into public.missions (id,track_slug,milestone,title,objective,estimated_minutes,tasks,commands,expected_outcome,hint,sort_order) values
('docker-environment','cloud-native-beginner','Prepare your Docker environment','Understand containers and verify Docker','Install Docker and explain why containers are useful.',35,'["Install Docker","Run docker --version","Run hello-world","Explain image versus container"]','["docker --version","docker run hello-world"]','Docker reports a version and hello-world completes successfully.','On Windows, start Docker Desktop before retrying.',0),
('docker-inspect-containers','cloud-native-beginner','Inspect and manage containers','Control a container lifecycle','List, inspect, log, stop, and remove a container.',40,'["List containers","Read logs","Inspect metadata","Stop and remove a container"]','["docker ps -a","docker logs hands-on-nginx","docker inspect hands-on-nginx","docker stop hands-on-nginx","docker rm hands-on-nginx"]','The practice container is inspected and safely removed.','Use docker ps -a when a stopped container is not shown by docker ps.',2)
on conflict (id) do nothing;
insert into public.missions (id,track_slug,milestone,title,objective,estimated_minutes,tasks,commands,expected_outcome,hint,sort_order) values
('python-environment','devops-beginner','Install and verify Python','Install and verify Python','Prepare an isolated Python runtime for the application.',60,'["Check Python","Create a virtual environment","Activate and verify"]','["python3 --version","python3 -m venv .venv","which python"]','Python is available inside an isolated environment.','Use the platform-specific activation command.',4),
('flask-application','devops-beginner','Build the Flask application','Build the Flask application','Create a small Flask service with real routes.',60,'["Create the application file","Run the service","Trace a request"]','["python -m py_compile app.py","flask --app app run --host 0.0.0.0 --port 5000","curl -i http://127.0.0.1:5000/health"]','The Flask service responds successfully.','Keep the server terminal open while testing.',6),
('mongodb-fundamentals','devops-beginner','Understand MongoDB and documents','Understand MongoDB and documents','Learn databases, collections, documents, and persistent data.',60,'["Understand the data model","Start and verify MongoDB","Create a sample document"]','["mongosh --eval ping","mongosh handson"]','A document is created and read back.','Check the MongoDB service before querying.',7),
('flask-mongodb-api','devops-beginner','Connect Flask to MongoDB','Connect Flask to MongoDB','Build POST and GET endpoints that persist notes.',60,'["Install the client library","Connect the application","Verify POST and GET"]','["pip install pymongo","export MONGODB_URI=...","curl http://127.0.0.1:5000/notes"]','Notes persist through the API.','Keep the connection string in an environment variable.',8),
('nginx-web-server','devops-beginner','Install and understand Nginx','Install and understand Nginx','Learn what a web server does.',60,'["Understand the request path","Install Nginx","Start and inspect it"]','["nginx -v","sudo systemctl start nginx","curl -I http://127.0.0.1"]','Nginx serves a successful response.','Use WSL2 or a Linux VM for Windows.',9),
('nginx-reverse-proxy','devops-beginner','Configure Nginx as a reverse proxy','Configure Nginx as a reverse proxy','Forward public traffic to Flask.',60,'["Create a server configuration","Enable and test safely","Reload and verify"]','["sudo nginx -t","sudo systemctl reload nginx","curl http://127.0.0.1/health"]','Nginx forwards requests to Flask.','Always run nginx -t before reload.',10),
('systemd-flask-service','devops-beginner','Run Flask as a system service','Run Flask as a system service','Manage Flask with systemd.',60,'["Understand a service unit","Create and start the unit","Read logs and restart"]','["sudo systemctl start handson-flask","sudo systemctl status handson-flask","sudo journalctl -u handson-flask"]','The service can be managed and inspected.', 'Read logs when status is failed.',11),
('stack-final-project','devops-beginner','Deploy the Notes stack','Deploy the Notes stack','Deploy Browser → Nginx → Flask → MongoDB.',90,'["Plan the architecture","Build and deploy","Capture production evidence"]','["systemctl is-active handson-flask","sudo nginx -t","curl http://127.0.0.1/notes"]','The Notes stack works through Nginx.', 'Capture evidence for every layer.',12),
('docker-images-dockerfile','cloud-native-beginner','Build your first Docker image','Build your first Docker image','Write a Dockerfile and build a repeatable image.',60,'["Understand the Dockerfile","Create the image","Run and test it"]','["docker build -t handson-demo:1.0 .","docker images","docker run --rm handson-demo:1.0"]','A custom image runs successfully.', 'Read every Dockerfile instruction.',4),
('docker-storage','cloud-native-beginner','Persist data with volumes','Persist data with volumes','Use volumes for data that must survive containers.',60,'["See ephemeral storage","Create and mount a volume","Inspect the volume"]','["docker volume create handson-data","docker volume inspect handson-data"]','Data survives container removal.', 'Do not edit Docker-managed mountpoints.',5),
('docker-networking','cloud-native-beginner','Connect containers on a network','Connect containers on a network','Use a Docker bridge network for service discovery.',60,'["Create a network","Run two services","Compare localhost and service names"]','["docker network create handson-net","docker network ls","curl http://web"]','Containers communicate by service name.', 'localhost inside a container is that container.',6),
('dockerize-flask','cloud-native-beginner','Containerize the Flask application','Containerize the Flask application','Move Flask into a reproducible container.',60,'["Review requirements","Write the Dockerfile","Build and test"]','["docker build -t handson-flask:1.0 .","docker run --rm -p 5000:5000 handson-flask:1.0"]','The containerized health endpoint responds.', 'Bind Flask to 0.0.0.0.',7),
('compose-introduction','cloud-native-beginner','Understand Docker Compose','Understand Docker Compose','Describe a multi-container workflow.',60,'["Map the stack","Create compose YAML","Start the stack"]','["docker compose config","docker compose up -d","docker compose ps"]','Compose starts the declared services.', 'YAML indentation matters.',8),
('compose-application','cloud-native-beginner','Compose Flask and MongoDB','Compose Flask and MongoDB','Build the full local application stack.',60,'["Configure the database URL","Add the database volume","Verify the request path"]','["docker compose up -d","curl http://localhost:5000/notes"]','API data persists through a restart.', 'Use the service name mongo.',9),
('compose-troubleshooting','cloud-native-beginner','Troubleshoot Docker Compose','Troubleshoot Docker Compose','Diagnose service, port, and networking failures.',60,'["Read service status","Read targeted logs","Test internal connectivity"]','["docker compose ps","docker compose logs --tail=50 app","docker compose exec app sh"]','A deliberate failure is diagnosed and fixed.', 'Separate symptom from cause.',10),
('compose-production-thinking','cloud-native-beginner','Prepare a reliable container stack','Prepare a reliable container stack','Add health checks, configuration hygiene, and restart behavior.',60,'["Separate configuration","Add health checks","Define restart and shutdown"]','["docker compose config","docker compose down","docker compose up -d"]','The stack restarts with data intact.', 'Keep secrets out of images.',11),
('docker-final-project','cloud-native-beginner','Build the final Docker project','Build the final Docker project','Deliver a containerized Flask and MongoDB application.',90,'["Define requirements","Implement and test","Submit a technical handoff"]','["docker compose up -d","docker compose ps","docker compose logs"]','The final stack and README are reproducible.', 'Document recovery steps.',12)
on conflict (id) do nothing;
insert into public.missions (id,track_slug,milestone,title,objective,estimated_minutes,tasks,commands,expected_outcome,hint,sort_order) values
('linux-files-permissions','devops-beginner','Work confidently with files and directories','Read, edit, and protect project files','Create a project structure, inspect permissions, and make a file executable.',45,'["Create a project structure","Read and edit a file","Inspect and change permissions"]','["mkdir -p ~/handson-workspace/project/logs","cat project/README.md","chmod u+x project/check.sh"]','The project structure exists and the script runs.','Work inside your home directory.',2),
('linux-processes-resources','devops-beginner','Understand processes and system resources','See what the system is doing','Inspect processes, memory, disk space, and a listening port.',45,'["Inspect running processes","Check memory and disk","Observe a background process"]','["ps -f","df -h .","sleep 30 &"]','You can identify a running process and available disk space.','Exact resource commands vary by operating system.',3),
('stack-troubleshooting','devops-beginner','Understand logs and troubleshoot the stack','Use a repeatable troubleshooting method','Practice diagnosing a failed command and isolate the problem.',45,'["Create a deliberate failure","Check the process and port","Write a diagnosis"]','["curl -i http://127.0.0.1:5999/health","ss -ltn","cat ~/handson-workspace/incident.md"]','Your incident note names a symptom, check, and next action.','Read the exact error before changing anything.',4)
on conflict (id) do nothing;
