import Link from 'next/link';
import {ArrowRight,Target} from 'lucide-react';
import {tracks} from '@/lib/tracks';
import {ProgressSummary} from '@/components/learning/progress-summary';

export const metadata={title:'Learning Hub'};

export default function Dashboard(){
  const active=tracks.filter(t=>t.available);
  return <div className="dash-content"><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'end',flexWrap:'wrap'}}><div><span className="eyebrow">Learning Hub</span><h1 style={{fontSize:'clamp(34px,5vw,56px)',letterSpacing:'-.07em',margin:'10px 0'}}>Keep building.</h1><p className="lede">Your next practical step is closer than you think.</p></div><span className="tag">Free courses</span></div><ProgressSummary total={3}/><section style={{marginTop:52}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{margin:0}}>Choose your next track</h2><Link href="/dashboard/tracks" className="mono" style={{fontSize:11,color:'var(--brand)'}}>View all →</Link></div><div className="grid dash-track-grid" style={{marginTop:20}}>{active.map(t=><article className="card" style={{padding:22}} key={t.slug}><span className="tag">{t.category}</span><h3 style={{fontSize:21,letterSpacing:'-.05em'}}>{t.title}</h3><p className="lede" style={{fontSize:13}}>{t.project}</p><p style={{fontSize:12,color:'var(--muted)'}}>Work through the guided missions at your own pace.</p><Link href={`/dashboard/tracks/${t.slug}`} className="btn btn-primary">Open track <ArrowRight size={16}/></Link></article>)}</div></section><section className="card" style={{padding:24,marginTop:38,display:'flex',gap:16,alignItems:'center'}}><Target color="var(--brand)"/><div><b>Start with one small mission</b><p className="lede" style={{fontSize:13,margin:4}}>Consistency beats intensity. Pick a track and make your first build today.</p></div></section><style>{`.dash-content{padding:48px clamp(20px,5vw,60px);max-width:1200px}.stat-grid{grid-template-columns:repeat(3,1fr)}.dash-track-grid{grid-template-columns:repeat(2,1fr)}@media(max-width:700px){.stat-grid,.dash-track-grid{grid-template-columns:1fr}.dash-content{padding:32px 18px}}`}</style></div>
}
