import Image from 'next/image';
import Link from 'next/link';
import {CalendarDays, ExternalLink, Users} from 'lucide-react';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import {eventTypeLabel, formatEventDate, isOpenForRegistration, type AcademyEvent} from '@/lib/events';
import {EventRegistrationForm} from '@/components/marketing/event-registration-form';
export const metadata = {title: 'Bootcamps & events', description: 'Apply for active HandsOn Academy bootcamps and webinars.'};
export default async function BootcampPage() {
  let events: AcademyEvent[] = [];
  if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) { const supabase = await createSupabaseServerClient(); const {data} = await supabase.from('events').select('*').eq('event_type', 'bootcamp').eq('is_active', true).order('event_starts_at', {ascending: true, nullsFirst: false}); events = (data || []) as AcademyEvent[]; }
  return <><section className="shell section" style={{paddingBottom: 40}}><span className="eyebrow">HandsOn Academy events</span><h1 style={{fontSize: 'clamp(44px,7vw,76px)', letterSpacing: '-.07em', marginBottom: 15}}>Build through a <i style={{fontStyle: 'normal', color: 'var(--accent)'}}>bootcamp.</i></h1><p className="lede" style={{fontSize: 17}}>Apply for an active cohort, learn with other builders, and receive every important detail by email.</p></section><section className="shell" style={{padding: '0 24px 88px'}}>{events.length === 0 ? <div className="card" style={{padding: 30, textAlign: 'center'}}><Users color="var(--brand)" size={28}/><h2 style={{fontSize: 28}}>No active bootcamp just yet.</h2><p className="lede" style={{margin: '0 auto 20px'}}>New cohorts will appear here as soon as applications open.</p><Link href="/community" className="btn btn-secondary">Join the community</Link></div> : <div className="grid" style={{gap: 32}}>{events.map(event => <article className="card event-card" key={event.id}><div className="event-flyer">{event.flyer_url ? <Image src={event.flyer_url} alt={`${event.title} flyer`} fill sizes="(max-width: 760px) 100vw, 430px" style={{objectFit: 'cover'}}/> : <div className="flyer-placeholder"><CalendarDays size={38}/><span>{eventTypeLabel(event.event_type)}</span></div>}</div><div style={{padding: 28}}><span className="tag">Active {eventTypeLabel(event.event_type)}</span><h2 style={{fontSize: 'clamp(29px,4vw,44px)', marginTop: 14}}>{event.title}</h2><p className="lede" style={{whiteSpace: 'pre-wrap'}}>{event.description}</p>{event.event_starts_at && <p style={{fontSize: 14, fontWeight: 700}}><CalendarDays size={16} style={{verticalAlign: 'text-bottom'}} /> Starts {formatEventDate(event.event_starts_at)}</p>}{event.application_deadline && <p style={{fontSize: 13, color: 'var(--muted)'}}>Applications close {formatEventDate(event.application_deadline)}</p>}{event.registration_mode === 'luma' ? <a className="btn btn-primary" href={event.luma_url!} target="_blank" rel="noreferrer">Apply on Luma <ExternalLink size={16}/></a> : isOpenForRegistration(event) ? <EventRegistrationForm event={event} /> : <p className="tag" style={{marginTop: 16}}>Applications closed</p>}</div></article>)}</div>}</section><style>{`.event-card{display:grid;grid-template-columns:minmax(260px,430px) 1fr;overflow:hidden}.event-flyer{min-height:390px;position:relative;background:#eaf5f1}.flyer-placeholder{height:100%;min-height:390px;display:grid;place-content:center;gap:13px;text-align:center;color:var(--brand);font:700 14px 'DM Mono',monospace;text-transform:uppercase;letter-spacing:.08em}@media(max-width:760px){.event-card{grid-template-columns:1fr}.event-flyer,.flyer-placeholder{min-height:300px}}`}</style></>;
}
